// Interest topics users can pick (max 20) — HelloTalk style.
export const INTERESTS: string[] = [
  "Movies",
  "Music",
  "Travel",
  "Food",
  "Cooking",
  "Photography",
  "Yoga",
  "Fitness",
  "Gaming",
  "Reading",
  "Art",
  "Dance",
  "Sports",
  "Football",
  "Basketball",
  "Cricket",
  "Technology",
  "Fashion",
  "Nature",
  "Pets",
  "Anime",
  "K-pop",
  "Coffee",
  "Hiking",
  "Swimming",
  "Meditation",
  "Business",
  "Science",
  "History",
  "Culture",
  "Volunteering",
  "Writing",
];

export const MAX_INTERESTS = 20;
